[versions]
guava = "33.3.1-jre"
kord = "0.15.0"
dotenv = "6.5.1"
spotify = "4.1.3"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kord = { module = "dev.kord:kord-core", version.ref = "kord" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
spotify = { module = "com.adamratzman:spotify-api-kotlin-core", version.ref = "spotify" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }